name: Техблог Егора Смолякова
email: yehors@ukr.net
author: Егор Смоляков
url: https://egorsmkv.github.io
baseurl: "/blog-ru"
meta_description: Заметки и размышления на технические и программистские темы. 
permalink: /:year/:month/:day/:title/
exclude: ['.idea', 'README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
timezone: "Europe/Kiev"
markdown: kramdown
